---
version: '3.2'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: inspector
      MYSQL_DATABASE: inspector
      MYSQL_USER: inspector
      MYSQL_PASSWORD: inspector
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio:/data:rw
    environment:
      MINIO_ACCESS_KEY: inspector
      MINIO_SECRET_KEY: inspector
    command:
    - server
    - /data
volumes:
  mysql:
  minio:
